### ISSUE TITLE
Proper placement of output files and log files

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#18]
We need to have proper placement of all output files generated by a submission - which include the zipped log files, predictions.cvs and results.json.

The files should be placed as in such a way that:
 1.  log files for a main submission should only be accessible by the queue admin and NOT submitter
 2. predicitions.csv should only be accessible by the by the queue admin and NOT submitter
 3. results.json should be accessible by the queue admin and the submitter

**Comment by Simon-Harris-IBM** [comment]
Modified line 110 & 130 of docker_agent_workflow.cwl such that parentid="#adminUploadSynId". This forces the stdout from running the docker image ("<submission_synid>_log.txt") and predictions.csv file to be placed into a LOCKED directory only the q admin can view. Which is good.
Also modified line 180 to parentid="#submitterUploadSynId" to upload the results.json using the submitter id.

The fact that we have a fanout mechanism complicates matters because the submitterid of the docker image to the main fanout queue is different to the submitterid to the main execution queue.

Let's focus initially on getting the files correctly placed/authorisations for the backend execution queue.

 - The log files for the submission ("<submission_synid>_logs.zip")  and results.json are placed into the default output directory. Usually this would mean that both these files are accessible by the submitter. But in this case, the submitter to the backend queue is an admin id and NOT the same as the submitter to the main fanout queue, these files are therefore not accessible by the original submitter, but we want to have the result.json file accessible to the original submitter.
 - predictions.csv and "<submission_synid>_log.txt" are placed into a _LOCKED directory, and are only accessible by the queue admin - which happens to be the same as the submitterid to the backend queue in my case.

Ideally, we want "<submission_synid>_logs.zip", "<submission_synid>_log.txt" & predictions.csv all in a single folder to which only the queue admin has access, and results.json in a folder which both the queue admin and original submitter have access to. 

@thomasyu888 Is this possible ?

**Comment by thomasyu888** [comment]
Ah, yes i totally forgot about this.  It is possible.  We would need to have a tool to obtain the lock and none lock folder of the submission from the fanout queue.   I will work on this sometimes tomorrow.

**Comment by Simon-Harris-IBM** [comment]
Thanks Tom.....
Having just talked with MIT, they also want to hide the toil log files in the 'express-lane'. All they want output is the stdout/stderr from the docker container.

**Comment by Simon-Harris-IBM** [comment]
Just to summarise, this is how we'd like to have the files placed:
 1. toil logs ("<submission_synid>_logs.zip") should not be accessible & hidden to participants
 2. predictions.csv should not be accessible & hidden to participants
 3. stdout/stderr from the docker containers ("<submission_synid>_log.txt") should be accessible to participants
 4. results.out should be accessible to participants

This should be the same for both express and main queues.
One potential issue is that 3. may create some security holes as participants will be able to submit an image to try and find/print the gold label file and then use this to cheat.

But we can discuss this internally. I think if we get the above layout working, we can fine tune it later.

Thanks....

**Comment by thomasyu888** [comment]
Thanks for the summary.  Here are my responses.

1.  I _think_ toil logs can be disabled by setting a .env parameter in the orchestrator. `SHARE_RESULTS_IMMEDIATELY=false`.  Unfortunately, this removes the text to tell participants where their log files are.
2. Upload this file into the `fanout` queue LOCK folder (not the LOCK folder generated by the main queues)
3.  You can upload this into the admin LOCK folder like point 2 above for the main queues, but give them to participants for the express lane submissions
4.  Upload this file into the `fanout` queue folder

I will need to write a tool to get the participants fanout `folder` and `folder-LOCK`.

**Comment by Simon-Harris-IBM** [comment]
I set `SHARE_RESULTS_IMMEDIATELY=false` in the .env files but all output files are now in the _LOCKED folder. There is nothing in the unlocked folder.
My understanding is the following line should have uploaded the results.json file into the unlocked folder:
```
  # Upload the validated scores so we have a record
  upload_validation:
    run: https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v2.1/upload_to_synapse.cwl
    in:
      - id: infile
        source: "#validate_and_score/results"
      - id: parentid
        #source: "#adminUploadSynId"
        source: "#get_docker_submission/submitter_synid"
      - id: used_entity
        source: "#get_docker_submission/entity_id"
      - id: executed_entity
        source: "#workflowSynapseId"
      - id: synapse_config
        source: "#synapseConfig"
    out:
      - id: uploaded_fileid
      - id: uploaded_file_version
      - id: results
```
See https://www.synapse.org/#!Synapse:syn21750580 for an example.

@thomasyu888 any idea what might be wrong ?
